# Generated by Django 4.2 on 2023-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Picture",
        ),
        migrations.AddField(
            model_name="author",
            name="picture",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fru.m.wikipedia.org%2Fwiki%2F%25D0%25A4%25D0%25B0%25D0%25B9%25D0%25BB%3ANo_foto.svg&psig=AOvVaw2W42tYfTtlIC6Sx2T49mFK&ust=1682714473990000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCICotYX2yv4CFQAAAAAdAAAAABAE",
                max_length=500,
                null=True,
            ),
        ),
    ]
